name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код
    - uses: actions/checkout@v3

    # 2. Устанавливаем CMake (Ubuntu уже имеет gcc/g++)
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    # 3. Конфигурируем сборку
    - name: Configure CMake
      run: cmake -S . -B build

    # 4. Собираем проект
    - name: Build
      run: cmake --build build
